spring.application.name=seat
server.port=${PORT:8080}

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-tiny-wind-atu68kj0.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iA6QBIWl4HMX
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

